home:
  pattern:  /
  defaults: { _controller: flflopupBundle:Default:index }

contact:
  pattern: /contact
  defaults:
    _controller: FrameworkBundle:Template:template
    template: 'flflopupBundle:Default:contact.html.twig'
