services:
#    flflopup.example:
#        class: fl\flopupBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    flflopup.session_idle:
        class: fl\flopupBundle\Handler\SessionIdleHandler
        arguments: ["@session", "@security.context", "@router", %session_max_idle_time%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }